/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.vistas;

import edu.cuc.modelo.producto;
import edu.cuc.modelo.productoDatos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaram
 */
public class DiseñoProductos extends javax.swing.JInternalFrame {

    productoDatos datos = new productoDatos();
    producto produc = new producto();
    DefaultTableModel modelo = new DefaultTableModel();
    int r;
    public DiseñoProductos() {
        initComponents();
        listarProducto();
    }
    
    void listarProducto() {
        modelo = (DefaultTableModel) tablaProductos.getModel();
        List<producto> lista = datos.listarProducto();
        Object[] object = new Object[5];
        for (int i = 0; i < lista.size(); i++) {
            object[0] = lista.get(i).getId();
            object[1] = lista.get(i).getNombre();
            object[2] = lista.get(i).getPrecio();
            object[3] = lista.get(i).getStock();
            object[4] = lista.get(i).getEstado();
            modelo.addRow(object);
        }
        tablaProductos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblNombreProducto = new javax.swing.JLabel();
        lblPrecioProducto = new javax.swing.JLabel();
        lblStockProducto = new javax.swing.JLabel();
        lblEstadoProducto = new javax.swing.JLabel();
        jcbEstadoProducto = new javax.swing.JComboBox<>();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        txtStockProducto = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnActualizarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNombreProducto.setText("Nombre Producto");
        jPanel2.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblPrecioProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPrecioProducto.setText("Precio");
        jPanel2.add(lblPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblStockProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblStockProducto.setText("Stock");
        jPanel2.add(lblStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblEstadoProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblEstadoProducto.setText("Estado");
        jPanel2.add(lblEstadoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jcbEstadoProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jcbEstadoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "0" }));
        jPanel2.add(jcbEstadoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, -1));
        jPanel2.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 260, -1));
        jPanel2.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 70, -1));
        jPanel2.add(txtStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 70, -1));

        btnAgregarProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/product.png"))); // NOI18N
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 40));

        btnEliminarProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/delete.png"))); // NOI18N
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, 40));

        btnActualizarProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnActualizarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/refresh.png"))); // NOI18N
        btnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, 40));

        btnNuevoProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/new.png"))); // NOI18N
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 150));

        tablaProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre Producto", "Precio", "Stock", "Estado"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 700, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/inventory.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
       agregarProductos();
       LimpiarTabla();
       listarProducto();
       nuevoProducto();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed
       actualizarProducto();
       LimpiarTabla();
       listarProducto();
       nuevoProducto();
    }//GEN-LAST:event_btnActualizarProductoActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
       nuevoProducto();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
      eliminarProducto();
      LimpiarTabla();
      listarProducto();
      nuevoProducto();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        int fila = tablaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila");
        }else{       
            String nom = tablaProductos.getValueAt(fila, 0).toString();
            String precio = tablaProductos.getValueAt(fila, 1).toString();
            String stock = tablaProductos.getValueAt(fila, 2).toString();
            String estado = tablaProductos.getValueAt(fila, 3).toString();
            txtNombreProducto.setText(nom);
            txtPrecioProducto.setText(precio);
            txtStockProducto.setText(stock);
            jcbEstadoProducto.setSelectedItem(estado);
        }
    }//GEN-LAST:event_tablaProductosMouseClicked
    
    void agregarProductos() {
        String nom = txtNombreProducto.getText();
        double pre = Double.parseDouble(txtPrecioProducto.getText());
        int stock = Integer.parseInt(txtStockProducto.getText());
        String estado = jcbEstadoProducto.getSelectedItem().toString();
        if (txtNombreProducto.getText().equals("") || txtPrecioProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese datos, por favor");
            txtNombreProducto.requestFocus();
            txtPrecioProducto.requestFocus();
            txtStockProducto.requestFocus();
        } else {
            produc.setNombre(nom);
            produc.setPrecio(pre);
            produc.setStock(stock);
            produc.setEstado(estado);
            datos.agregar(produc);
            r=datos.actualizar(produc);
             if(r==0){
                JOptionPane.showMessageDialog(this, "Producto agregado con exito..!!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Error");
            } 
        }
     }
    

    void actualizarProducto() {
        int fila = tablaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        } else {
            int id = Integer.parseInt(tablaProductos.getValueAt(fila, 0).toString());
            String nom = txtNombreProducto.getText();
            double pre = Double.parseDouble(txtPrecioProducto.getText());
            int stock = Integer.parseInt(txtStockProducto.getText());
            String estado = jcbEstadoProducto.getSelectedItem().toString();
            produc.setNombre(nom);
            produc.setPrecio(pre);
            produc.setStock(stock);
            produc.setEstado(estado);
            produc.setId(id);
            datos.actualizar(produc);
            JOptionPane.showMessageDialog(this, "Producto actualizado con exito");
        }
    }

    void eliminarProducto() {
        int fila = tablaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        } else {
            int id = Integer.parseInt(tablaProductos.getValueAt(fila, 0).toString());
            datos.delete(id);
            JOptionPane.showMessageDialog(this, "Producto eliminado");
        }
    }

    void nuevoProducto() {
        txtNombreProducto.setText("");
        txtPrecioProducto.setText("");
        txtStockProducto.setText("");
        jcbEstadoProducto.setSelectedItem("Seleccionar");
        txtNombreProducto.requestFocus();
    }

    void LimpiarTabla() {
        for (int i = 0; i < tablaProductos.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbEstadoProducto;
    private javax.swing.JLabel lblEstadoProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblStockProducto;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtStockProducto;
    // End of variables declaration//GEN-END:variables
}
