/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.vistas;

import edu.cuc.modelo.cliente;
import edu.cuc.modelo.clienteDatos;
import edu.cuc.modelo.detalleVenta;
import edu.cuc.modelo.producto;
import edu.cuc.modelo.productoDatos;
import edu.cuc.modelo.vendedor;
import edu.cuc.modelo.vendedorDatos;
import edu.cuc.modelo.ventas;
import edu.cuc.modelo.ventasDatos;
import java.security.Principal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Jaram
 */
public class DiseñoVentas extends javax.swing.JInternalFrame {

    ventasDatos vdatos = new ventasDatos();
    clienteDatos cdatos = new clienteDatos();
    productoDatos pdatos = new productoDatos();
    
    producto p = new producto();
    ventas v = new ventas();
    detalleVenta dv = new detalleVenta();
    cliente cl = new cliente();

    DefaultTableModel modelo = new DefaultTableModel();
    int idp;
    int cant;
    int item;
    int idve;
    double pre;
    double tpagar;

    public DiseñoVentas() {
        initComponents();
        generarSerie();
        fecha();
        txtVendedor.setText("Andres Felipe Jaramillo Gonzalez");
        
    }
    
    void fecha() {
        Calendar calendar = new GregorianCalendar();
        txtFecha.setText("" + calendar.get(Calendar.YEAR) + "-" + calendar.get(Calendar.MONTH) + "-" + calendar.get(Calendar.DAY_OF_MONTH));
    }
    
    void generarSerie() {
        String serie = vdatos.NroSerieVentas();
        if (serie.equals("")) {
            txtNumeroSerie.setText("0000001");
        } else {
            int increment = Integer.parseInt(serie);
            increment = increment + 1;
            txtNumeroSerie.setText("000000" + increment);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloNegocio = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblTelefonoGuia = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroSerie = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblCodigoCliente = new javax.swing.JLabel();
        lblCodigoProducto = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtCodigoProducto = new javax.swing.JTextField();
        btbBuscarCliente = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        lblClienteVenta = new javax.swing.JLabel();
        lblProductoVenta = new javax.swing.JLabel();
        txtClienteVenta = new javax.swing.JTextField();
        txtProductoVenta = new javax.swing.JTextField();
        lblPrecioProducto = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblStockProducto = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        btnAgregarPrecio = new javax.swing.JButton();
        lblCantidadProducto = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JSpinner();
        lblVendedor = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        btnGenerarVenta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestor Ventas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloNegocio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTituloNegocio.setText("PUNTO FRIO \"DONDE DUBYS\"");
        jPanel1.add(lblTituloNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        lblSubTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSubTitulo.setText("Venta De Productos");
        jPanel1.add(lblSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        lblTelefonoGuia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTelefonoGuia.setText("Tel: 3114067396 ");
        jPanel1.add(lblTelefonoGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        lblNumeroSerie.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNumeroSerie.setText("NRO SERIE");
        jPanel1.add(lblNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/beer.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/knife-fork-and-plate.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        txtNumeroSerie.setEditable(false);
        jPanel1.add(txtNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigoCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCodigoCliente.setText("COD CLIENTE:");
        jPanel2.add(lblCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        lblCodigoProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCodigoProducto.setText("COD PRODUCTO:");
        jPanel2.add(lblCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel2.add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, -1));
        jPanel2.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 60, -1));

        btbBuscarCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        btbBuscarCliente.setText("BUSCAR");
        btbBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBuscarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btbBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        btnBuscarProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        btnBuscarProducto.setText("BUSCAR");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        lblClienteVenta.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblClienteVenta.setText("CLIENTE:");
        jPanel2.add(lblClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        lblProductoVenta.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblProductoVenta.setText("PRODUCTO:");
        jPanel2.add(lblProductoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 20));
        jPanel2.add(txtClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 200, -1));
        jPanel2.add(txtProductoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 200, -1));

        lblPrecioProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblPrecioProducto.setText("PRECIO:");
        jPanel2.add(lblPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, -1));

        lblStockProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblStockProducto.setText("STOCK:");
        jPanel2.add(lblStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 70, -1));

        btnAgregarPrecio.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        btnAgregarPrecio.setText("AGREGAR");
        btnAgregarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 90, -1));

        lblCantidadProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCantidadProducto.setText("CANTIDAD:");
        jPanel2.add(lblCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 30));

        lblVendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblVendedor.setText("VENDEDOR:");
        jPanel2.add(lblVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));
        jPanel2.add(txtVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 200, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("FECHA:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 170, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 620, 180));

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalle);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 620, 200));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setText("TOTAL A PAGAR");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));
        jPanel3.add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 90, 30));

        btnGenerarVenta.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnGenerarVenta.setText("GENERAR VENTA");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });
        jPanel3.add(btnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 620, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarClienteActionPerformed
        buscarCliente();
    }//GEN-LAST:event_btbBuscarClienteActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        buscarProducto();
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPrecioActionPerformed
        agregarProducto();
    }//GEN-LAST:event_btnAgregarPrecioActionPerformed

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        if (txtTotalPagar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar datos");
        } else {
            guardarVenta();
            guardarDetalle();
            actualizarStock();            
            JOptionPane.showMessageDialog(this, "Se realizo con exito");
            nuevo();
            generarSerie();
        }
    }//GEN-LAST:event_btnGenerarVentaActionPerformed

    void nuevo(){
        limpiarTabla();
        txtCodigoCliente.setText("");
        txtClienteVenta.setText("");
        txtCantidad.setValue(1);
        txtCodigoProducto.setText("");
        txtPrecio.setText("");
        txtProductoVenta.setText("");
        txtStock.setText("");
        txtTotalPagar.setText("");
        txtCodigoCliente.requestFocus();
    }
    
    void limpiarTabla(){
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
    
    void actualizarStock() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            producto pr = new producto();
            idp = Integer.parseInt(tablaDetalle.getValueAt(i, 1).toString());
            cant = Integer.parseInt(tablaDetalle.getValueAt(i, 3).toString());
            pr = pdatos.listarID(idp);
            int sa = pr.getStock() - cant;
            pdatos.actualizarStock(sa, idp);
        }
    }

    void guardarVenta() {
        int idv = 1;
        int idc = cl.getId();
        String serie = txtNumeroSerie.getText();
        String fecha = txtFecha.getText();
        double monto = tpagar;
        String estado = "1";
        v.setIdCliente(idc);
        v.setIdVendedor(idv);
        v.setSerie(serie);
        v.setFecha(fecha);
        v.setMonto(monto);
        v.setEstado(estado);
        vdatos.GuardarVentas(v);

    }

    void guardarDetalle() {
        String idv = vdatos.IdVentas();
        int idve = Integer.parseInt(idv);
        for (int i = 0; i < tablaDetalle.getRowCount(); i++) {
            idp = Integer.parseInt(tablaDetalle.getValueAt(i, 1).toString());
            cant = Integer.parseInt(tablaDetalle.getValueAt(i, 3).toString());
            pre = Double.parseDouble(tablaDetalle.getValueAt(i, 4).toString());
            dv.setIdVentas(idve);
            dv.setIdProducto(idp);
            dv.setCantidad(cant);
            dv.setPreVenta(pre);
            vdatos.GuardarDetalleVentas(dv);
        }
    }

    void agregarProducto() {
        double total;
        modelo = (DefaultTableModel) tablaDetalle.getModel();
        item = item + 1;
        idp = p.getId();
        String nomp = txtProductoVenta.getText();
        pre = Double.parseDouble(txtPrecio.getText());
        cant = Integer.parseInt(txtCantidad.getValue().toString());
        int stock = Integer.parseInt(txtStock.getText());
        total = cant * pre;
        ArrayList lista = new ArrayList();
        if (stock > 0) {
            lista.add(item);
            lista.add(idp);
            lista.add(nomp);
            lista.add(cant);
            lista.add(pre);
            lista.add(total);
            Object[] ob = new Object[6];
            ob[0] = lista.get(0);
            ob[1] = lista.get(1);
            ob[2] = lista.get(2);
            ob[3] = lista.get(3);
            ob[4] = lista.get(4);
            ob[5] = lista.get(5);
            modelo.addRow(ob);
            tablaDetalle.setModel(modelo);
            calculatTotal();
        } else {
            JOptionPane.showMessageDialog(this, "Stock producto no disponible");
        }
    }

    void calculatTotal() {
        tpagar = 0;
        for (int i = 0; i < tablaDetalle.getRowCount(); i++) {
            cant = Integer.parseInt(tablaDetalle.getValueAt(i, 3).toString());
            pre = Double.parseDouble(tablaDetalle.getValueAt(i, 4).toString());
            tpagar = tpagar + (cant * pre);
        }
        txtTotalPagar.setText("" + tpagar + "0");
    }

    void buscarProducto() {
        int id = Integer.parseInt(txtCodigoProducto.getText());
        if (txtCodigoProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el codigo producto");
        } else {
            p = pdatos.listarID(id);
            if (p.getId() != 0) {
                txtProductoVenta.setText(p.getNombre());
                txtPrecio.setText("" + p.getPrecio());
                txtStock.setText("" + p.getStock());
            } else {
                JOptionPane.showMessageDialog(this, "Producto no registrado");
                txtCodigoProducto.requestFocus();
            }
        }
    }

    void buscarCliente() {
        int r;
        String cod = txtCodigoCliente.getText();
        if (txtCodigoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar codigo cliente");
        } else {
            cl = cdatos.listarID(cod);
            if (cl.getDni() != null) {
                txtClienteVenta.setText(cl.getNombre());
                txtCodigoProducto.requestFocus();
            } else {
                r = JOptionPane.showConfirmDialog(this, "Cliente no registrado, ¿desea registrar?");
                if (r == 0) {
                    Diseñocliente cf = new Diseñocliente();
                    DiseñoSistema.ventanaPrincipal.add(cf);
                    cf.setVisible(true);
                }
            }

        }
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbBuscarCliente;
    private javax.swing.JButton btnAgregarPrecio;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnGenerarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadProducto;
    private javax.swing.JLabel lblClienteVenta;
    private javax.swing.JLabel lblCodigoCliente;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblProductoVenta;
    private javax.swing.JLabel lblStockProducto;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTelefonoGuia;
    private javax.swing.JLabel lblTituloNegocio;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JSpinner txtCantidad;
    private javax.swing.JTextField txtClienteVenta;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProductoVenta;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
