/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.vistas;

import edu.cuc.modelo.vendedor;
import edu.cuc.modelo.vendedorDatos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaram
 */
public class DiseñoVendedor extends javax.swing.JInternalFrame {

    vendedorDatos datos = new vendedorDatos();
    vendedor vd = new vendedor();
    DefaultTableModel modelo = new DefaultTableModel();
    int r;
    public DiseñoVendedor() {
        initComponents();
        listarVendedor();
        
    }
    void listarVendedor() {
        modelo = (DefaultTableModel) tablaVendedor.getModel();
        List<vendedor> lista = datos.listarVendedor();
        Object[] object = new Object[6];
        for (int i = 0; i < lista.size(); i++) {
            object[0] = lista.get(i).getIdVendedor();
            object[1] = lista.get(i).getDni();
            object[2] = lista.get(i).getNombre();
            object[3] = lista.get(i).getTelefono();
            object[4] = lista.get(i).getEstado();
            object[5] = lista.get(i).getUsuario();
            modelo.addRow(object);
        }
        tablaVendedor.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        lblNombreCompletoVendedor = new javax.swing.JLabel();
        lblTelefonoVendedor = new javax.swing.JLabel();
        lblEstadoVendedor = new javax.swing.JLabel();
        txtDNIVendedor = new javax.swing.JTextField();
        txtNombreVendedor = new javax.swing.JTextField();
        txtTelefonoVendedor = new javax.swing.JTextField();
        jbcEstadoVendedor = new javax.swing.JComboBox<>();
        btnAgregarVendedor = new javax.swing.JButton();
        btnEliminarVendedor = new javax.swing.JButton();
        btnModificarVendedor = new javax.swing.JButton();
        btnNuevoVendedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedor = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vendedor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/contact.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDNI.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblDNI.setText("DNI");
        jPanel2.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblNombreCompletoVendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNombreCompletoVendedor.setText("Nombre Completo");
        jPanel2.add(lblNombreCompletoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblTelefonoVendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTelefonoVendedor.setText("Telefono");
        jPanel2.add(lblTelefonoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblEstadoVendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblEstadoVendedor.setText("Estado");
        jPanel2.add(lblEstadoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel2.add(txtDNIVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, -1));
        jPanel2.add(txtNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 220, -1));
        jPanel2.add(txtTelefonoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));

        jbcEstadoVendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jbcEstadoVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "0" }));
        jPanel2.add(jbcEstadoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 110, -1));

        btnAgregarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/contactVendedor.png"))); // NOI18N
        btnAgregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVendedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 60, -1));

        btnEliminarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/delete.png"))); // NOI18N
        btnEliminarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVendedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, 40));

        btnModificarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/refresh.png"))); // NOI18N
        btnModificarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVendedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 60, 40));

        btnNuevoVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/add-contact.png"))); // NOI18N
        btnNuevoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVendedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 620, 150));

        tablaVendedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaVendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tablaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Nombre Completo", "Telefono", "Estado", "Usuario"
            }
        ));
        jScrollPane1.setViewportView(tablaVendedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 620, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVendedorActionPerformed
        agregarVendedor();
        LimpiarTabla();
        listarVendedor();
        nuevo();
    }//GEN-LAST:event_btnAgregarVendedorActionPerformed

    private void btnEliminarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVendedorActionPerformed
        eliminarVendedor();
        LimpiarTabla();
        listarVendedor();
        nuevo();
    }//GEN-LAST:event_btnEliminarVendedorActionPerformed

    private void btnModificarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVendedorActionPerformed
        modificarVendedor();
        LimpiarTabla();
        listarVendedor();
        nuevo();
    }//GEN-LAST:event_btnModificarVendedorActionPerformed

    private void btnNuevoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVendedorActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoVendedorActionPerformed
     
    void agregarVendedor() {
        String nom = txtNombreVendedor.getText();
        String dni = txtDNIVendedor.getText();
        String tel = txtTelefonoVendedor.getText();
        String estado = jbcEstadoVendedor.getSelectedItem().toString();
        String user = nom.substring(0, 2).concat(dni.substring(0, 2));
        if (txtNombreVendedor.getText().equals("") || txtDNIVendedor.getText().equals("") || txtTelefonoVendedor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese datos, por favor");
            txtNombreVendedor.requestFocus();
            txtDNIVendedor.requestFocus();
            txtTelefonoVendedor.requestFocus();
        } else {
        vd.setDni(dni);
        vd.setNombre(nom);
        vd.setTelefono(tel);
        vd.setEstado(estado);
        vd.setUsuario(user);
        datos.agregarVendedor(vd);
        r=datos.actualizarVendedor(vd);
    }if(r==0){
        JOptionPane.showMessageDialog(this, "Vendedor agregado con exito..!!");
    }else{
        JOptionPane.showMessageDialog(this, "Error");
    }
  }
    
    void eliminarVendedor(){
        int fila = tablaVendedor.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila");
        } else {
            int id = Integer.parseInt(tablaVendedor.getValueAt(fila, 0).toString());
            datos.eliminarVendedor(id);
            JOptionPane.showMessageDialog(this, "Vendedor Eliminado");
        } 
    }
    
    void modificarVendedor() {
        int fila = tablaVendedor.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        } else {
            int id = Integer.parseInt(modelo.getValueAt(fila, 0).toString());
            String dni = txtDNIVendedor.getText();
            String nom = txtNombreVendedor.getText();            
            String tel=txtTelefonoVendedor.getText();
            String estado = jbcEstadoVendedor.getSelectedItem().toString();            
            vd.setDni(dni);
            vd.setNombre(nom);
            vd.setTelefono(tel);
            vd.setEstado(estado);
            vd.setIdVendedor(id);
            r=datos.actualizarVendedor(vd);
            if(r==1){
                JOptionPane.showMessageDialog(this, "Vendedor actualizado con exito..!!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Error");
            } 
        }
    }

    void nuevo() {
        txtNombreVendedor.setText("");
        txtDNIVendedor.setText("");
        txtTelefonoVendedor.setText("");
        jbcEstadoVendedor.setSelectedIndex(0); 
        txtDNIVendedor.requestFocus();
    }

    void LimpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVendedor;
    private javax.swing.JButton btnEliminarVendedor;
    private javax.swing.JButton btnModificarVendedor;
    private javax.swing.JButton btnNuevoVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jbcEstadoVendedor;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblEstadoVendedor;
    private javax.swing.JLabel lblNombreCompletoVendedor;
    private javax.swing.JLabel lblTelefonoVendedor;
    private javax.swing.JTable tablaVendedor;
    private javax.swing.JTextField txtDNIVendedor;
    private javax.swing.JTextField txtNombreVendedor;
    private javax.swing.JTextField txtTelefonoVendedor;
    // End of variables declaration//GEN-END:variables
}
