/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.vistas;

import edu.cuc.modelo.cliente;
import edu.cuc.modelo.clienteDatos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaram
 */
public class Diseñocliente extends javax.swing.JInternalFrame {

    clienteDatos datos = new clienteDatos();
    cliente cl = new cliente();
    DefaultTableModel modelo = new DefaultTableModel();
    int id;

    public Diseñocliente() {
        initComponents();
        listar();
    }

    void listar() {
        List<cliente> listar = datos.listar();
        modelo = (DefaultTableModel) tblCliente.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < listar.size(); i++) {
            ob[0] = listar.get(i).getId();
            ob[1] = listar.get(i).getDni();
            ob[2] = listar.get(i).getNombre();
            ob[3] = listar.get(i).getDireccion();
            ob[4] = listar.get(i).getEstado();
            modelo.addRow(ob);
        }
        tblCliente.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        lbDireccionCliente = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombreCompleto = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jcbEstadoCLiente = new javax.swing.JComboBox<>();
        btnAgregarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/employee.png"))); // NOI18N
        jPanel1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(224, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDNI.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblDNI.setText("DNI");
        jPanel2.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblNombreCompleto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNombreCompleto.setText("Nombre Completo");
        jPanel2.add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbDireccionCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lbDireccionCliente.setText("Direccion");
        jPanel2.add(lbDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblEstado.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblEstado.setText("Estado");
        jPanel2.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 140, -1));
        jPanel2.add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, -1));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 300, -1));

        jcbEstadoCLiente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jcbEstadoCLiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1 ", "0" }));
        jPanel2.add(jcbEstadoCLiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 110, -1));

        btnAgregarCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/customer.png"))); // NOI18N
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, 40));

        btnActualizarCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/refresh.png"))); // NOI18N
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, 40));

        btnEliminarCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/delete.png"))); // NOI18N
        btnEliminarCliente.setMaximumSize(new java.awt.Dimension(139, 33));
        btnEliminarCliente.setMinimumSize(new java.awt.Dimension(139, 33));
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, 40));

        btnNuevoCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/add-group.png"))); // NOI18N
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 790, 170));

        tblCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Nombre Completo", "Direccion", "Estado"
            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 790, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        agregarCliente();
        limpiarTabla();
        listar();
        nuevoCliente();
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        nuevoCliente();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        actualizarCliente();
        limpiarTabla();
        listar();
        nuevoCliente();
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        eliminarCliente();
        limpiarTabla();
        listar();
        nuevoCliente();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        int fila = tblCliente.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila");
        } else {
            id = Integer.parseInt(tblCliente.getValueAt(fila, 0).toString());
            String dni = tblCliente.getValueAt(fila, 1).toString();
            String nom = tblCliente.getValueAt(fila, 2).toString();
            String dir = tblCliente.getValueAt(fila, 3).toString();
            String es = tblCliente.getValueAt(fila, 4).toString();
            txtDNI.setText(dni);
            txtNombreCompleto.setText(nom);
            txtDireccion.setText(dir);
            jcbEstadoCLiente.setSelectedItem(es);
    }//GEN-LAST:event_tblClienteMouseClicked
    }

    public void agregarCliente() {
        String dni = txtDNI.getText();
        String nom = txtNombreCompleto.getText();
        String dir = txtDireccion.getText();
        String es = jcbEstadoCLiente.getSelectedItem().toString();
        if (txtDNI.getText().equals("") || txtNombreCompleto.getText().equals("") || txtDireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese datos, por favor");
            txtDNI.requestFocus();
            txtNombreCompleto.requestFocus();
            txtDireccion.requestFocus();
        } else {
            Object[] ob = new Object[4];
            ob[0] = dni;
            ob[1] = nom;
            ob[2] = dir;
            ob[3] = es;
            datos.agregar(ob);
        }
    }
 
    void actualizarCliente() {
        int fila = tblCliente.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe selecionar una Fila");
        } else {
            String dni = txtDNI.getText();
            String nom = txtNombreCompleto.getText();
            String dir = txtDireccion.getText();
            String es = jcbEstadoCLiente.getSelectedItem().toString();
            Object[] obj = new Object[5];
            obj[0] = dni;
            obj[1] = nom;
            obj[2] = dir;
            obj[3] = es;
            obj[4] = id;
            datos.actualizar(obj);
        }

    }

    void eliminarCliente() {
        int fila = tblCliente.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fila");
        } else {
            datos.eliminar(id);
        }
    }

    void nuevoCliente() {
        txtNombreCompleto.setText("");
        txtDireccion.setText("");
        txtDNI.setText("");
        jcbEstadoCLiente.setSelectedItem("Seleccionar");
        txtDNI.requestFocus();
    }

    void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbEstadoCLiente;
    private javax.swing.JLabel lbDireccionCliente;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreCompleto;
    // End of variables declaration//GEN-END:variables
}
