/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.vistas;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author Jaram
 */
public class DiseñoSistema extends javax.swing.JFrame {


    public DiseñoSistema() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        subMenuAyuda = new javax.swing.JMenuItem();
        subMenuFinalizar = new javax.swing.JMenuItem();
        subMenuVentas = new javax.swing.JMenu();
        menuGenerarVentas = new javax.swing.JMenuItem();
        menuHerramientas = new javax.swing.JMenu();
        subMenuCliente = new javax.swing.JMenuItem();
        subMenuProducto = new javax.swing.JMenuItem();
        subMenuVendedor = new javax.swing.JMenuItem();
        menuReporte = new javax.swing.JMenu();
        subMenuReporteVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        menuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/list.png"))); // NOI18N
        menuPrincipal.setText("Menu");
        menuPrincipal.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        subMenuAyuda.setText("Ayuda");
        menuPrincipal.add(subMenuAyuda);

        subMenuFinalizar.setText("Finalizar");
        subMenuFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuFinalizarActionPerformed(evt);
            }
        });
        menuPrincipal.add(subMenuFinalizar);

        jMenuBar1.add(menuPrincipal);

        subMenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/payment-method.png"))); // NOI18N
        subMenuVentas.setText("Ventas");
        subMenuVentas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        menuGenerarVentas.setText("Generar Ventas");
        menuGenerarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarVentasActionPerformed(evt);
            }
        });
        subMenuVentas.add(menuGenerarVentas);

        jMenuBar1.add(subMenuVentas);

        menuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/customer-support.png"))); // NOI18N
        menuHerramientas.setText("Herramientas");
        menuHerramientas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        subMenuCliente.setText("Cliente");
        subMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuClienteActionPerformed(evt);
            }
        });
        menuHerramientas.add(subMenuCliente);

        subMenuProducto.setText("Producto");
        subMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuProductoActionPerformed(evt);
            }
        });
        menuHerramientas.add(subMenuProducto);

        subMenuVendedor.setText("Vendedor");
        subMenuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuVendedorActionPerformed(evt);
            }
        });
        menuHerramientas.add(subMenuVendedor);

        jMenuBar1.add(menuHerramientas);

        menuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/imagenes/social-care.png"))); // NOI18N
        menuReporte.setText("Reportes");
        menuReporte.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        subMenuReporteVentas.setText("Reporte Ventas");
        menuReporte.add(subMenuReporteVentas);

        jMenuBar1.add(menuReporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuFinalizarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_subMenuFinalizarActionPerformed

    private void menuGenerarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarVentasActionPerformed
        DiseñoVentas vt = new DiseñoVentas();
        centrarVentanas(vt);
        
    }//GEN-LAST:event_menuGenerarVentasActionPerformed

    private void subMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuClienteActionPerformed
        Diseñocliente cl = new Diseñocliente();
        centrarVentanas(cl);
    }//GEN-LAST:event_subMenuClienteActionPerformed

    private void subMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuProductoActionPerformed
        DiseñoProductos pr = new DiseñoProductos();
        centrarVentanas(pr);
    }//GEN-LAST:event_subMenuProductoActionPerformed

    private void subMenuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuVendedorActionPerformed
        DiseñoVendedor vd = new DiseñoVendedor();
        centrarVentanas(vd);
    }//GEN-LAST:event_subMenuVendedorActionPerformed
       
    void centrarVentanas(JInternalFrame frame){
        ventanaPrincipal.add(frame);
        Dimension dimension = ventanaPrincipal.getSize();
        Dimension fventas = frame.getSize();
        frame.setLocation((dimension.width -fventas.width)/2,(dimension.height -fventas.height)/2);
        frame.show();
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuGenerarVentas;
    private javax.swing.JMenu menuHerramientas;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuReporte;
    private javax.swing.JMenuItem subMenuAyuda;
    private javax.swing.JMenuItem subMenuCliente;
    private javax.swing.JMenuItem subMenuFinalizar;
    private javax.swing.JMenuItem subMenuProducto;
    private javax.swing.JMenuItem subMenuReporteVentas;
    private javax.swing.JMenuItem subMenuVendedor;
    private javax.swing.JMenu subMenuVentas;
    public static javax.swing.JDesktopPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
